// Code generated by rclgo-gen. DO NOT EDIT.

package vision_msgs_msg
import (
	"unsafe"

	"github.com/ATIinc/rclgo/pkg/rclgo"
	"github.com/ATIinc/rclgo/pkg/rclgo/types"
	"github.com/ATIinc/rclgo/pkg/rclgo/typemap"
	std_msgs_msg "github.com/iema-group/goros2/msgs/std_msgs/msg"
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <vision_msgs/msg/bounding_box2_d_array.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("vision_msgs/BoundingBox2DArray", BoundingBox2DArrayTypeSupport)
	typemap.RegisterMessage("vision_msgs/msg/BoundingBox2DArray", BoundingBox2DArrayTypeSupport)
}

type BoundingBox2DArray struct {
	Header std_msgs_msg.Header `yaml:"header" json:"header" mapstructure:"header"`
	Boxes []BoundingBox2D `yaml:"boxes" json:"boxes" mapstructure:"boxes"`
}

// NewBoundingBox2DArray creates a new BoundingBox2DArray with default values.
func NewBoundingBox2DArray() *BoundingBox2DArray {
	self := BoundingBox2DArray{}
	self.SetDefaults()
	return &self
}

func (t *BoundingBox2DArray) Clone() *BoundingBox2DArray {
	c := &BoundingBox2DArray{}
	c.Header = *t.Header.Clone()
	if t.Boxes != nil {
		c.Boxes = make([]BoundingBox2D, len(t.Boxes))
		CloneBoundingBox2DSlice(c.Boxes, t.Boxes)
	}
	return c
}

func (t *BoundingBox2DArray) CloneMsg() types.Message {
	return t.Clone()
}

func (t *BoundingBox2DArray) SetDefaults() {
	t.Header.SetDefaults()
	t.Boxes = nil
}

func (t *BoundingBox2DArray) GetTypeSupport() types.MessageTypeSupport {
	return BoundingBox2DArrayTypeSupport
}

// BoundingBox2DArrayPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type BoundingBox2DArrayPublisher struct {
	*rclgo.Publisher
}

// NewBoundingBox2DArrayPublisher creates and returns a new publisher for the
// BoundingBox2DArray
func NewBoundingBox2DArrayPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*BoundingBox2DArrayPublisher, error) {
	pub, err := node.NewPublisher(topic_name, BoundingBox2DArrayTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &BoundingBox2DArrayPublisher{pub}, nil
}

func (p *BoundingBox2DArrayPublisher) Publish(msg *BoundingBox2DArray) error {
	return p.Publisher.Publish(msg)
}

// BoundingBox2DArraySubscription wraps rclgo.Subscription to provide type safe helper
// functions
type BoundingBox2DArraySubscription struct {
	*rclgo.Subscription
}

// BoundingBox2DArraySubscriptionCallback type is used to provide a subscription
// handler function for a BoundingBox2DArraySubscription.
type BoundingBox2DArraySubscriptionCallback func(msg *BoundingBox2DArray, info *rclgo.MessageInfo, err error)

// NewBoundingBox2DArraySubscription creates and returns a new subscription for the
// BoundingBox2DArray
func NewBoundingBox2DArraySubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback BoundingBox2DArraySubscriptionCallback) (*BoundingBox2DArraySubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg BoundingBox2DArray
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, BoundingBox2DArrayTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &BoundingBox2DArraySubscription{sub}, nil
}

func (s *BoundingBox2DArraySubscription) TakeMessage(out *BoundingBox2DArray) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneBoundingBox2DArraySlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneBoundingBox2DArraySlice(dst, src []BoundingBox2DArray) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var BoundingBox2DArrayTypeSupport types.MessageTypeSupport = _BoundingBox2DArrayTypeSupport{}

type _BoundingBox2DArrayTypeSupport struct{}

func (t _BoundingBox2DArrayTypeSupport) New() types.Message {
	return NewBoundingBox2DArray()
}

func (t _BoundingBox2DArrayTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.vision_msgs__msg__BoundingBox2DArray
	return (unsafe.Pointer)(C.vision_msgs__msg__BoundingBox2DArray__create())
}

func (t _BoundingBox2DArrayTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.vision_msgs__msg__BoundingBox2DArray__destroy((*C.vision_msgs__msg__BoundingBox2DArray)(pointer_to_free))
}

func (t _BoundingBox2DArrayTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*BoundingBox2DArray)
	mem := (*C.vision_msgs__msg__BoundingBox2DArray)(dst)
	std_msgs_msg.HeaderTypeSupport.AsCStruct(unsafe.Pointer(&mem.header), &m.Header)
	BoundingBox2D__Sequence_to_C(&mem.boxes, m.Boxes)
}

func (t _BoundingBox2DArrayTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*BoundingBox2DArray)
	mem := (*C.vision_msgs__msg__BoundingBox2DArray)(ros2_message_buffer)
	std_msgs_msg.HeaderTypeSupport.AsGoStruct(&m.Header, unsafe.Pointer(&mem.header))
	BoundingBox2D__Sequence_to_Go(&m.Boxes, mem.boxes)
}

func (t _BoundingBox2DArrayTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__vision_msgs__msg__BoundingBox2DArray())
}

type CBoundingBox2DArray = C.vision_msgs__msg__BoundingBox2DArray
type CBoundingBox2DArray__Sequence = C.vision_msgs__msg__BoundingBox2DArray__Sequence

func BoundingBox2DArray__Sequence_to_Go(goSlice *[]BoundingBox2DArray, cSlice CBoundingBox2DArray__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]BoundingBox2DArray, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		BoundingBox2DArrayTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func BoundingBox2DArray__Sequence_to_C(cSlice *CBoundingBox2DArray__Sequence, goSlice []BoundingBox2DArray) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.vision_msgs__msg__BoundingBox2DArray)(C.malloc(C.sizeof_struct_vision_msgs__msg__BoundingBox2DArray * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		BoundingBox2DArrayTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func BoundingBox2DArray__Array_to_Go(goSlice []BoundingBox2DArray, cSlice []CBoundingBox2DArray) {
	for i := 0; i < len(cSlice); i++ {
		BoundingBox2DArrayTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func BoundingBox2DArray__Array_to_C(cSlice []CBoundingBox2DArray, goSlice []BoundingBox2DArray) {
	for i := 0; i < len(goSlice); i++ {
		BoundingBox2DArrayTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
