# Automatically generated by: ros2nix --distro jazzy --flake
{ lib, buildRosPackage, ament-cmake, ament-lint-auto, ament-lint-common, geometry-msgs, rclc }:
buildRosPackage rec {
  pname = "ros-jazzy-ros-gz-go-application";
  version = "0.0.0";

  src = ./.;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  checkInputs = [ ament-lint-auto ament-lint-common ];
  propagatedBuildInputs = [ geometry-msgs rclc ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "TODO: Package description";
    license = with lib.licenses; [ "TODO-License-declaration" ];
  };
}
