// Code generated by rclgo-gen. DO NOT EDIT.

package composition_interfaces_srv
import (
	"unsafe"

	"github.com/ATIinc/rclgo/pkg/rclgo"
	"github.com/ATIinc/rclgo/pkg/rclgo/types"
	"github.com/ATIinc/rclgo/pkg/rclgo/typemap"
	primitives "github.com/ATIinc/rclgo/pkg/rclgo/primitives"
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <composition_interfaces/srv/unload_node.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("composition_interfaces/UnloadNode_Response", UnloadNode_ResponseTypeSupport)
	typemap.RegisterMessage("composition_interfaces/srv/UnloadNode_Response", UnloadNode_ResponseTypeSupport)
}

type UnloadNode_Response struct {
	Success bool `yaml:"success" json:"success" mapstructure:"success"`// True if the node existed and was unloaded.
	ErrorMessage string `yaml:"error_message" json:"error_message" mapstructure:"error_message"`// Human readable error message if success is false, else empty string.
}

// NewUnloadNode_Response creates a new UnloadNode_Response with default values.
func NewUnloadNode_Response() *UnloadNode_Response {
	self := UnloadNode_Response{}
	self.SetDefaults()
	return &self
}

func (t *UnloadNode_Response) Clone() *UnloadNode_Response {
	c := &UnloadNode_Response{}
	c.Success = t.Success
	c.ErrorMessage = t.ErrorMessage
	return c
}

func (t *UnloadNode_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *UnloadNode_Response) SetDefaults() {
	t.Success = false
	t.ErrorMessage = ""
}

func (t *UnloadNode_Response) GetTypeSupport() types.MessageTypeSupport {
	return UnloadNode_ResponseTypeSupport
}

// UnloadNode_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type UnloadNode_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewUnloadNode_ResponsePublisher creates and returns a new publisher for the
// UnloadNode_Response
func NewUnloadNode_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*UnloadNode_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, UnloadNode_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &UnloadNode_ResponsePublisher{pub}, nil
}

func (p *UnloadNode_ResponsePublisher) Publish(msg *UnloadNode_Response) error {
	return p.Publisher.Publish(msg)
}

// UnloadNode_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type UnloadNode_ResponseSubscription struct {
	*rclgo.Subscription
}

// UnloadNode_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a UnloadNode_ResponseSubscription.
type UnloadNode_ResponseSubscriptionCallback func(msg *UnloadNode_Response, info *rclgo.MessageInfo, err error)

// NewUnloadNode_ResponseSubscription creates and returns a new subscription for the
// UnloadNode_Response
func NewUnloadNode_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback UnloadNode_ResponseSubscriptionCallback) (*UnloadNode_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg UnloadNode_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, UnloadNode_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &UnloadNode_ResponseSubscription{sub}, nil
}

func (s *UnloadNode_ResponseSubscription) TakeMessage(out *UnloadNode_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneUnloadNode_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneUnloadNode_ResponseSlice(dst, src []UnloadNode_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var UnloadNode_ResponseTypeSupport types.MessageTypeSupport = _UnloadNode_ResponseTypeSupport{}

type _UnloadNode_ResponseTypeSupport struct{}

func (t _UnloadNode_ResponseTypeSupport) New() types.Message {
	return NewUnloadNode_Response()
}

func (t _UnloadNode_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.composition_interfaces__srv__UnloadNode_Response
	return (unsafe.Pointer)(C.composition_interfaces__srv__UnloadNode_Response__create())
}

func (t _UnloadNode_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.composition_interfaces__srv__UnloadNode_Response__destroy((*C.composition_interfaces__srv__UnloadNode_Response)(pointer_to_free))
}

func (t _UnloadNode_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*UnloadNode_Response)
	mem := (*C.composition_interfaces__srv__UnloadNode_Response)(dst)
	mem.success = C.bool(m.Success)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.error_message), m.ErrorMessage)
}

func (t _UnloadNode_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*UnloadNode_Response)
	mem := (*C.composition_interfaces__srv__UnloadNode_Response)(ros2_message_buffer)
	m.Success = bool(mem.success)
	primitives.StringAsGoStruct(&m.ErrorMessage, unsafe.Pointer(&mem.error_message))
}

func (t _UnloadNode_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__composition_interfaces__srv__UnloadNode_Response())
}

type CUnloadNode_Response = C.composition_interfaces__srv__UnloadNode_Response
type CUnloadNode_Response__Sequence = C.composition_interfaces__srv__UnloadNode_Response__Sequence

func UnloadNode_Response__Sequence_to_Go(goSlice *[]UnloadNode_Response, cSlice CUnloadNode_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]UnloadNode_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		UnloadNode_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func UnloadNode_Response__Sequence_to_C(cSlice *CUnloadNode_Response__Sequence, goSlice []UnloadNode_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.composition_interfaces__srv__UnloadNode_Response)(C.malloc(C.sizeof_struct_composition_interfaces__srv__UnloadNode_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		UnloadNode_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func UnloadNode_Response__Array_to_Go(goSlice []UnloadNode_Response, cSlice []CUnloadNode_Response) {
	for i := 0; i < len(cSlice); i++ {
		UnloadNode_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func UnloadNode_Response__Array_to_C(cSlice []CUnloadNode_Response, goSlice []UnloadNode_Response) {
	for i := 0; i < len(goSlice); i++ {
		UnloadNode_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
