// Code generated by rclgo-gen. DO NOT EDIT.

package geometry_msgs_msg

/*
#cgo LDFLAGS: "-L/nix/store/0crsiaif8jk4lw9ga7rvpssdw1g1dzgp-ros-env/lib" "-Wl,-rpath=/nix/store/0crsiaif8jk4lw9ga7rvpssdw1g1dzgp-ros-env/lib"

#cgo LDFLAGS: -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lgeometry_msgs__rosidl_typesupport_c -lgeometry_msgs__rosidl_generator_c
#cgo LDFLAGS: -lstd_msgs__rosidl_typesupport_c -lstd_msgs__rosidl_generator_c

#cgo CFLAGS: "-I/nix/store/0crsiaif8jk4lw9ga7rvpssdw1g1dzgp-ros-env/include/action_msgs"
#cgo CFLAGS: "-I/nix/store/0crsiaif8jk4lw9ga7rvpssdw1g1dzgp-ros-env/include/builtin_interfaces"
#cgo CFLAGS: "-I/nix/store/0crsiaif8jk4lw9ga7rvpssdw1g1dzgp-ros-env/include/example_interfaces"
#cgo CFLAGS: "-I/nix/store/0crsiaif8jk4lw9ga7rvpssdw1g1dzgp-ros-env/include/geometry_msgs"
#cgo CFLAGS: "-I/nix/store/0crsiaif8jk4lw9ga7rvpssdw1g1dzgp-ros-env/include/rcutils"
#cgo CFLAGS: "-I/nix/store/0crsiaif8jk4lw9ga7rvpssdw1g1dzgp-ros-env/include/rosidl_dynamic_typesupport"
#cgo CFLAGS: "-I/nix/store/0crsiaif8jk4lw9ga7rvpssdw1g1dzgp-ros-env/include/rosidl_runtime_c"
#cgo CFLAGS: "-I/nix/store/0crsiaif8jk4lw9ga7rvpssdw1g1dzgp-ros-env/include/rosidl_typesupport_interface"
#cgo CFLAGS: "-I/nix/store/0crsiaif8jk4lw9ga7rvpssdw1g1dzgp-ros-env/include/sensor_msgs"
#cgo CFLAGS: "-I/nix/store/0crsiaif8jk4lw9ga7rvpssdw1g1dzgp-ros-env/include/service_msgs"
#cgo CFLAGS: "-I/nix/store/0crsiaif8jk4lw9ga7rvpssdw1g1dzgp-ros-env/include/std_msgs"
#cgo CFLAGS: "-I/nix/store/0crsiaif8jk4lw9ga7rvpssdw1g1dzgp-ros-env/include/std_srvs"
#cgo CFLAGS: "-I/nix/store/0crsiaif8jk4lw9ga7rvpssdw1g1dzgp-ros-env/include/type_description_interfaces"
#cgo CFLAGS: "-I/nix/store/0crsiaif8jk4lw9ga7rvpssdw1g1dzgp-ros-env/include/unique_identifier_msgs"
#cgo CFLAGS: "-I/nix/store/0crsiaif8jk4lw9ga7rvpssdw1g1dzgp-ros-env/include/std_msgs"

#cgo CFLAGS: "-I/nix/store/0crsiaif8jk4lw9ga7rvpssdw1g1dzgp-ros-env/include/geometry_msgs"
*/
import "C"
