// Code generated by rclgo-gen. DO NOT EDIT.

package statistics_msgs_msg
import (
	"unsafe"

	"github.com/ATIinc/rclgo/pkg/rclgo"
	"github.com/ATIinc/rclgo/pkg/rclgo/types"
	"github.com/ATIinc/rclgo/pkg/rclgo/typemap"
	primitives "github.com/ATIinc/rclgo/pkg/rclgo/primitives"
	builtin_interfaces_msg "github.com/iema-group/goros2/msgs/builtin_interfaces/msg"
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <statistics_msgs/msg/metrics_message.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("statistics_msgs/MetricsMessage", MetricsMessageTypeSupport)
	typemap.RegisterMessage("statistics_msgs/msg/MetricsMessage", MetricsMessageTypeSupport)
}

type MetricsMessage struct {
	MeasurementSourceName string `yaml:"measurement_source_name" json:"measurement_source_name" mapstructure:"measurement_source_name"`// Name metric measurement source, e.g., node, topic, or process name
	MetricsSource string `yaml:"metrics_source" json:"metrics_source" mapstructure:"metrics_source"`// Name of the metric being measured, e.g. cpu_percentage, free_memory_mb, message_age, etc.
	Unit string `yaml:"unit" json:"unit" mapstructure:"unit"`// Unit of measure of the metric, e.g. percent, mb, seconds, etc.
	WindowStart builtin_interfaces_msg.Time `yaml:"window_start" json:"window_start" mapstructure:"window_start"`// Measurement window start time
	WindowStop builtin_interfaces_msg.Time `yaml:"window_stop" json:"window_stop" mapstructure:"window_stop"`// Measurement window end time
	Statistics []StatisticDataPoint `yaml:"statistics" json:"statistics" mapstructure:"statistics"`// A list of statistics data point, defined in StatisticDataPoint.msg
}

// NewMetricsMessage creates a new MetricsMessage with default values.
func NewMetricsMessage() *MetricsMessage {
	self := MetricsMessage{}
	self.SetDefaults()
	return &self
}

func (t *MetricsMessage) Clone() *MetricsMessage {
	c := &MetricsMessage{}
	c.MeasurementSourceName = t.MeasurementSourceName
	c.MetricsSource = t.MetricsSource
	c.Unit = t.Unit
	c.WindowStart = *t.WindowStart.Clone()
	c.WindowStop = *t.WindowStop.Clone()
	if t.Statistics != nil {
		c.Statistics = make([]StatisticDataPoint, len(t.Statistics))
		CloneStatisticDataPointSlice(c.Statistics, t.Statistics)
	}
	return c
}

func (t *MetricsMessage) CloneMsg() types.Message {
	return t.Clone()
}

func (t *MetricsMessage) SetDefaults() {
	t.MeasurementSourceName = ""
	t.MetricsSource = ""
	t.Unit = ""
	t.WindowStart.SetDefaults()
	t.WindowStop.SetDefaults()
	t.Statistics = nil
}

func (t *MetricsMessage) GetTypeSupport() types.MessageTypeSupport {
	return MetricsMessageTypeSupport
}

// MetricsMessagePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type MetricsMessagePublisher struct {
	*rclgo.Publisher
}

// NewMetricsMessagePublisher creates and returns a new publisher for the
// MetricsMessage
func NewMetricsMessagePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*MetricsMessagePublisher, error) {
	pub, err := node.NewPublisher(topic_name, MetricsMessageTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &MetricsMessagePublisher{pub}, nil
}

func (p *MetricsMessagePublisher) Publish(msg *MetricsMessage) error {
	return p.Publisher.Publish(msg)
}

// MetricsMessageSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type MetricsMessageSubscription struct {
	*rclgo.Subscription
}

// MetricsMessageSubscriptionCallback type is used to provide a subscription
// handler function for a MetricsMessageSubscription.
type MetricsMessageSubscriptionCallback func(msg *MetricsMessage, info *rclgo.MessageInfo, err error)

// NewMetricsMessageSubscription creates and returns a new subscription for the
// MetricsMessage
func NewMetricsMessageSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback MetricsMessageSubscriptionCallback) (*MetricsMessageSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg MetricsMessage
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, MetricsMessageTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &MetricsMessageSubscription{sub}, nil
}

func (s *MetricsMessageSubscription) TakeMessage(out *MetricsMessage) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneMetricsMessageSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneMetricsMessageSlice(dst, src []MetricsMessage) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var MetricsMessageTypeSupport types.MessageTypeSupport = _MetricsMessageTypeSupport{}

type _MetricsMessageTypeSupport struct{}

func (t _MetricsMessageTypeSupport) New() types.Message {
	return NewMetricsMessage()
}

func (t _MetricsMessageTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.statistics_msgs__msg__MetricsMessage
	return (unsafe.Pointer)(C.statistics_msgs__msg__MetricsMessage__create())
}

func (t _MetricsMessageTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.statistics_msgs__msg__MetricsMessage__destroy((*C.statistics_msgs__msg__MetricsMessage)(pointer_to_free))
}

func (t _MetricsMessageTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*MetricsMessage)
	mem := (*C.statistics_msgs__msg__MetricsMessage)(dst)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.measurement_source_name), m.MeasurementSourceName)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.metrics_source), m.MetricsSource)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.unit), m.Unit)
	builtin_interfaces_msg.TimeTypeSupport.AsCStruct(unsafe.Pointer(&mem.window_start), &m.WindowStart)
	builtin_interfaces_msg.TimeTypeSupport.AsCStruct(unsafe.Pointer(&mem.window_stop), &m.WindowStop)
	StatisticDataPoint__Sequence_to_C(&mem.statistics, m.Statistics)
}

func (t _MetricsMessageTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*MetricsMessage)
	mem := (*C.statistics_msgs__msg__MetricsMessage)(ros2_message_buffer)
	primitives.StringAsGoStruct(&m.MeasurementSourceName, unsafe.Pointer(&mem.measurement_source_name))
	primitives.StringAsGoStruct(&m.MetricsSource, unsafe.Pointer(&mem.metrics_source))
	primitives.StringAsGoStruct(&m.Unit, unsafe.Pointer(&mem.unit))
	builtin_interfaces_msg.TimeTypeSupport.AsGoStruct(&m.WindowStart, unsafe.Pointer(&mem.window_start))
	builtin_interfaces_msg.TimeTypeSupport.AsGoStruct(&m.WindowStop, unsafe.Pointer(&mem.window_stop))
	StatisticDataPoint__Sequence_to_Go(&m.Statistics, mem.statistics)
}

func (t _MetricsMessageTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__statistics_msgs__msg__MetricsMessage())
}

type CMetricsMessage = C.statistics_msgs__msg__MetricsMessage
type CMetricsMessage__Sequence = C.statistics_msgs__msg__MetricsMessage__Sequence

func MetricsMessage__Sequence_to_Go(goSlice *[]MetricsMessage, cSlice CMetricsMessage__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]MetricsMessage, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		MetricsMessageTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func MetricsMessage__Sequence_to_C(cSlice *CMetricsMessage__Sequence, goSlice []MetricsMessage) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.statistics_msgs__msg__MetricsMessage)(C.malloc(C.sizeof_struct_statistics_msgs__msg__MetricsMessage * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		MetricsMessageTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func MetricsMessage__Array_to_Go(goSlice []MetricsMessage, cSlice []CMetricsMessage) {
	for i := 0; i < len(cSlice); i++ {
		MetricsMessageTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func MetricsMessage__Array_to_C(cSlice []CMetricsMessage, goSlice []MetricsMessage) {
	for i := 0; i < len(goSlice); i++ {
		MetricsMessageTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
