// Code generated by rclgo-gen. DO NOT EDIT.

package tf2_msgs_action
import (
	"unsafe"

	"github.com/ATIinc/rclgo/pkg/rclgo"
	"github.com/ATIinc/rclgo/pkg/rclgo/types"
	"github.com/ATIinc/rclgo/pkg/rclgo/typemap"
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <tf2_msgs/action/lookup_transform.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("tf2_msgs/LookupTransform_GetResult_Response", LookupTransform_GetResult_ResponseTypeSupport)
	typemap.RegisterMessage("tf2_msgs/action/LookupTransform_GetResult_Response", LookupTransform_GetResult_ResponseTypeSupport)
}

type LookupTransform_GetResult_Response struct {
	Status int8 `yaml:"status" json:"status" mapstructure:"status"`
	Result LookupTransform_Result `yaml:"result" json:"result" mapstructure:"result"`
}

// NewLookupTransform_GetResult_Response creates a new LookupTransform_GetResult_Response with default values.
func NewLookupTransform_GetResult_Response() *LookupTransform_GetResult_Response {
	self := LookupTransform_GetResult_Response{}
	self.SetDefaults()
	return &self
}

func (t *LookupTransform_GetResult_Response) Clone() *LookupTransform_GetResult_Response {
	c := &LookupTransform_GetResult_Response{}
	c.Status = t.Status
	c.Result = *t.Result.Clone()
	return c
}

func (t *LookupTransform_GetResult_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *LookupTransform_GetResult_Response) SetDefaults() {
	t.Status = 0
	t.Result.SetDefaults()
}

func (t *LookupTransform_GetResult_Response) GetTypeSupport() types.MessageTypeSupport {
	return LookupTransform_GetResult_ResponseTypeSupport
}

// LookupTransform_GetResult_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type LookupTransform_GetResult_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewLookupTransform_GetResult_ResponsePublisher creates and returns a new publisher for the
// LookupTransform_GetResult_Response
func NewLookupTransform_GetResult_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*LookupTransform_GetResult_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, LookupTransform_GetResult_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &LookupTransform_GetResult_ResponsePublisher{pub}, nil
}

func (p *LookupTransform_GetResult_ResponsePublisher) Publish(msg *LookupTransform_GetResult_Response) error {
	return p.Publisher.Publish(msg)
}

// LookupTransform_GetResult_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type LookupTransform_GetResult_ResponseSubscription struct {
	*rclgo.Subscription
}

// LookupTransform_GetResult_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a LookupTransform_GetResult_ResponseSubscription.
type LookupTransform_GetResult_ResponseSubscriptionCallback func(msg *LookupTransform_GetResult_Response, info *rclgo.MessageInfo, err error)

// NewLookupTransform_GetResult_ResponseSubscription creates and returns a new subscription for the
// LookupTransform_GetResult_Response
func NewLookupTransform_GetResult_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback LookupTransform_GetResult_ResponseSubscriptionCallback) (*LookupTransform_GetResult_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg LookupTransform_GetResult_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, LookupTransform_GetResult_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &LookupTransform_GetResult_ResponseSubscription{sub}, nil
}

func (s *LookupTransform_GetResult_ResponseSubscription) TakeMessage(out *LookupTransform_GetResult_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneLookupTransform_GetResult_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneLookupTransform_GetResult_ResponseSlice(dst, src []LookupTransform_GetResult_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var LookupTransform_GetResult_ResponseTypeSupport types.MessageTypeSupport = _LookupTransform_GetResult_ResponseTypeSupport{}

type _LookupTransform_GetResult_ResponseTypeSupport struct{}

func (t _LookupTransform_GetResult_ResponseTypeSupport) New() types.Message {
	return NewLookupTransform_GetResult_Response()
}

func (t _LookupTransform_GetResult_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.tf2_msgs__action__LookupTransform_GetResult_Response
	return (unsafe.Pointer)(C.tf2_msgs__action__LookupTransform_GetResult_Response__create())
}

func (t _LookupTransform_GetResult_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.tf2_msgs__action__LookupTransform_GetResult_Response__destroy((*C.tf2_msgs__action__LookupTransform_GetResult_Response)(pointer_to_free))
}

func (t _LookupTransform_GetResult_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*LookupTransform_GetResult_Response)
	mem := (*C.tf2_msgs__action__LookupTransform_GetResult_Response)(dst)
	mem.status = C.int8_t(m.Status)
	LookupTransform_ResultTypeSupport.AsCStruct(unsafe.Pointer(&mem.result), &m.Result)
}

func (t _LookupTransform_GetResult_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*LookupTransform_GetResult_Response)
	mem := (*C.tf2_msgs__action__LookupTransform_GetResult_Response)(ros2_message_buffer)
	m.Status = int8(mem.status)
	LookupTransform_ResultTypeSupport.AsGoStruct(&m.Result, unsafe.Pointer(&mem.result))
}

func (t _LookupTransform_GetResult_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__tf2_msgs__action__LookupTransform_GetResult_Response())
}

type CLookupTransform_GetResult_Response = C.tf2_msgs__action__LookupTransform_GetResult_Response
type CLookupTransform_GetResult_Response__Sequence = C.tf2_msgs__action__LookupTransform_GetResult_Response__Sequence

func LookupTransform_GetResult_Response__Sequence_to_Go(goSlice *[]LookupTransform_GetResult_Response, cSlice CLookupTransform_GetResult_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]LookupTransform_GetResult_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		LookupTransform_GetResult_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func LookupTransform_GetResult_Response__Sequence_to_C(cSlice *CLookupTransform_GetResult_Response__Sequence, goSlice []LookupTransform_GetResult_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.tf2_msgs__action__LookupTransform_GetResult_Response)(C.malloc(C.sizeof_struct_tf2_msgs__action__LookupTransform_GetResult_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		LookupTransform_GetResult_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func LookupTransform_GetResult_Response__Array_to_Go(goSlice []LookupTransform_GetResult_Response, cSlice []CLookupTransform_GetResult_Response) {
	for i := 0; i < len(cSlice); i++ {
		LookupTransform_GetResult_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func LookupTransform_GetResult_Response__Array_to_C(cSlice []CLookupTransform_GetResult_Response, goSlice []LookupTransform_GetResult_Response) {
	for i := 0; i < len(goSlice); i++ {
		LookupTransform_GetResult_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
