// Code generated by rclgo-gen. DO NOT EDIT.

package shape_msgs_msg
import (
	"unsafe"

	"github.com/ATIinc/rclgo/pkg/rclgo"
	"github.com/ATIinc/rclgo/pkg/rclgo/types"
	"github.com/ATIinc/rclgo/pkg/rclgo/typemap"
	primitives "github.com/ATIinc/rclgo/pkg/rclgo/primitives"
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <shape_msgs/msg/mesh_triangle.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("shape_msgs/MeshTriangle", MeshTriangleTypeSupport)
	typemap.RegisterMessage("shape_msgs/msg/MeshTriangle", MeshTriangleTypeSupport)
}

type MeshTriangle struct {
	VertexIndices [3]uint32 `yaml:"vertex_indices" json:"vertex_indices" mapstructure:"vertex_indices"`
}

// NewMeshTriangle creates a new MeshTriangle with default values.
func NewMeshTriangle() *MeshTriangle {
	self := MeshTriangle{}
	self.SetDefaults()
	return &self
}

func (t *MeshTriangle) Clone() *MeshTriangle {
	c := &MeshTriangle{}
	c.VertexIndices = t.VertexIndices
	return c
}

func (t *MeshTriangle) CloneMsg() types.Message {
	return t.Clone()
}

func (t *MeshTriangle) SetDefaults() {
	t.VertexIndices = [3]uint32{}
}

func (t *MeshTriangle) GetTypeSupport() types.MessageTypeSupport {
	return MeshTriangleTypeSupport
}

// MeshTrianglePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type MeshTrianglePublisher struct {
	*rclgo.Publisher
}

// NewMeshTrianglePublisher creates and returns a new publisher for the
// MeshTriangle
func NewMeshTrianglePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*MeshTrianglePublisher, error) {
	pub, err := node.NewPublisher(topic_name, MeshTriangleTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &MeshTrianglePublisher{pub}, nil
}

func (p *MeshTrianglePublisher) Publish(msg *MeshTriangle) error {
	return p.Publisher.Publish(msg)
}

// MeshTriangleSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type MeshTriangleSubscription struct {
	*rclgo.Subscription
}

// MeshTriangleSubscriptionCallback type is used to provide a subscription
// handler function for a MeshTriangleSubscription.
type MeshTriangleSubscriptionCallback func(msg *MeshTriangle, info *rclgo.MessageInfo, err error)

// NewMeshTriangleSubscription creates and returns a new subscription for the
// MeshTriangle
func NewMeshTriangleSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback MeshTriangleSubscriptionCallback) (*MeshTriangleSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg MeshTriangle
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, MeshTriangleTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &MeshTriangleSubscription{sub}, nil
}

func (s *MeshTriangleSubscription) TakeMessage(out *MeshTriangle) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneMeshTriangleSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneMeshTriangleSlice(dst, src []MeshTriangle) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var MeshTriangleTypeSupport types.MessageTypeSupport = _MeshTriangleTypeSupport{}

type _MeshTriangleTypeSupport struct{}

func (t _MeshTriangleTypeSupport) New() types.Message {
	return NewMeshTriangle()
}

func (t _MeshTriangleTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.shape_msgs__msg__MeshTriangle
	return (unsafe.Pointer)(C.shape_msgs__msg__MeshTriangle__create())
}

func (t _MeshTriangleTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.shape_msgs__msg__MeshTriangle__destroy((*C.shape_msgs__msg__MeshTriangle)(pointer_to_free))
}

func (t _MeshTriangleTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*MeshTriangle)
	mem := (*C.shape_msgs__msg__MeshTriangle)(dst)
	cSlice_vertex_indices := mem.vertex_indices[:]
	primitives.Uint32__Array_to_C(*(*[]primitives.CUint32)(unsafe.Pointer(&cSlice_vertex_indices)), m.VertexIndices[:])
}

func (t _MeshTriangleTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*MeshTriangle)
	mem := (*C.shape_msgs__msg__MeshTriangle)(ros2_message_buffer)
	cSlice_vertex_indices := mem.vertex_indices[:]
	primitives.Uint32__Array_to_Go(m.VertexIndices[:], *(*[]primitives.CUint32)(unsafe.Pointer(&cSlice_vertex_indices)))
}

func (t _MeshTriangleTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__shape_msgs__msg__MeshTriangle())
}

type CMeshTriangle = C.shape_msgs__msg__MeshTriangle
type CMeshTriangle__Sequence = C.shape_msgs__msg__MeshTriangle__Sequence

func MeshTriangle__Sequence_to_Go(goSlice *[]MeshTriangle, cSlice CMeshTriangle__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]MeshTriangle, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		MeshTriangleTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func MeshTriangle__Sequence_to_C(cSlice *CMeshTriangle__Sequence, goSlice []MeshTriangle) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.shape_msgs__msg__MeshTriangle)(C.malloc(C.sizeof_struct_shape_msgs__msg__MeshTriangle * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		MeshTriangleTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func MeshTriangle__Array_to_Go(goSlice []MeshTriangle, cSlice []CMeshTriangle) {
	for i := 0; i < len(cSlice); i++ {
		MeshTriangleTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func MeshTriangle__Array_to_C(cSlice []CMeshTriangle, goSlice []MeshTriangle) {
	for i := 0; i < len(goSlice); i++ {
		MeshTriangleTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
