// Code generated by rclgo-gen. DO NOT EDIT.

package diagnostic_msgs_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <diagnostic_msgs/srv/add_diagnostics.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/ATIinc/rclgo/pkg/rclgo"
	"github.com/ATIinc/rclgo/pkg/rclgo/typemap"
	"github.com/ATIinc/rclgo/pkg/rclgo/types"
)

func init() {
	typemap.RegisterService("diagnostic_msgs/AddDiagnostics", AddDiagnosticsTypeSupport)
	typemap.RegisterService("diagnostic_msgs/srv/AddDiagnostics", AddDiagnosticsTypeSupport)
}

type _AddDiagnosticsTypeSupport struct {}

func (s _AddDiagnosticsTypeSupport) Request() types.MessageTypeSupport {
	return AddDiagnostics_RequestTypeSupport
}

func (s _AddDiagnosticsTypeSupport) Response() types.MessageTypeSupport {
	return AddDiagnostics_ResponseTypeSupport
}

func (s _AddDiagnosticsTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__diagnostic_msgs__srv__AddDiagnostics())
}

// Modifying this variable is undefined behavior.
var AddDiagnosticsTypeSupport types.ServiceTypeSupport = _AddDiagnosticsTypeSupport{}

// AddDiagnosticsClient wraps rclgo.Client to provide type safe helper
// functions
type AddDiagnosticsClient struct {
	*rclgo.Client
}

// NewAddDiagnosticsClient creates and returns a new client for the
// AddDiagnostics
func NewAddDiagnosticsClient(node *rclgo.Node, serviceName string, options *rclgo.ClientOptions) (*AddDiagnosticsClient, error) {
	client, err := node.NewClient(serviceName, AddDiagnosticsTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &AddDiagnosticsClient{client}, nil
}

func (s *AddDiagnosticsClient) Send(ctx context.Context, req *AddDiagnostics_Request) (*AddDiagnostics_Response, *rclgo.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*AddDiagnostics_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type AddDiagnosticsServiceResponseSender struct {
	sender rclgo.ServiceResponseSender
}

func (s AddDiagnosticsServiceResponseSender) SendResponse(resp *AddDiagnostics_Response) error {
	return s.sender.SendResponse(resp)
}

type AddDiagnosticsServiceRequestHandler func(*rclgo.ServiceInfo, *AddDiagnostics_Request, AddDiagnosticsServiceResponseSender)

// AddDiagnosticsService wraps rclgo.Service to provide type safe helper
// functions
type AddDiagnosticsService struct {
	*rclgo.Service
}

// NewAddDiagnosticsService creates and returns a new service for the
// AddDiagnostics
func NewAddDiagnosticsService(node *rclgo.Node, name string, options *rclgo.ServiceOptions, handler AddDiagnosticsServiceRequestHandler) (*AddDiagnosticsService, error) {
	h := func(rmw *rclgo.ServiceInfo, msg types.Message, rs rclgo.ServiceResponseSender) {
		m := msg.(*AddDiagnostics_Request)
		responseSender := AddDiagnosticsServiceResponseSender{sender: rs}
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, AddDiagnosticsTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &AddDiagnosticsService{service}, nil
}
