// Code generated by rclgo-gen. DO NOT EDIT.

package map_msgs_srv
import (
	"unsafe"

	"github.com/ATIinc/rclgo/pkg/rclgo"
	"github.com/ATIinc/rclgo/pkg/rclgo/types"
	"github.com/ATIinc/rclgo/pkg/rclgo/typemap"
	sensor_msgs_msg "github.com/iema-group/goros2/msgs/sensor_msgs/msg"
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <map_msgs/srv/get_point_map.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("map_msgs/GetPointMap_Response", GetPointMap_ResponseTypeSupport)
	typemap.RegisterMessage("map_msgs/srv/GetPointMap_Response", GetPointMap_ResponseTypeSupport)
}

type GetPointMap_Response struct {
	Map sensor_msgs_msg.PointCloud2 `yaml:"map" json:"map" mapstructure:"map"`// Get the map as a sensor_msgs/PointCloud2
}

// NewGetPointMap_Response creates a new GetPointMap_Response with default values.
func NewGetPointMap_Response() *GetPointMap_Response {
	self := GetPointMap_Response{}
	self.SetDefaults()
	return &self
}

func (t *GetPointMap_Response) Clone() *GetPointMap_Response {
	c := &GetPointMap_Response{}
	c.Map = *t.Map.Clone()
	return c
}

func (t *GetPointMap_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *GetPointMap_Response) SetDefaults() {
	t.Map.SetDefaults()
}

func (t *GetPointMap_Response) GetTypeSupport() types.MessageTypeSupport {
	return GetPointMap_ResponseTypeSupport
}

// GetPointMap_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type GetPointMap_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewGetPointMap_ResponsePublisher creates and returns a new publisher for the
// GetPointMap_Response
func NewGetPointMap_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*GetPointMap_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, GetPointMap_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &GetPointMap_ResponsePublisher{pub}, nil
}

func (p *GetPointMap_ResponsePublisher) Publish(msg *GetPointMap_Response) error {
	return p.Publisher.Publish(msg)
}

// GetPointMap_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type GetPointMap_ResponseSubscription struct {
	*rclgo.Subscription
}

// GetPointMap_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a GetPointMap_ResponseSubscription.
type GetPointMap_ResponseSubscriptionCallback func(msg *GetPointMap_Response, info *rclgo.MessageInfo, err error)

// NewGetPointMap_ResponseSubscription creates and returns a new subscription for the
// GetPointMap_Response
func NewGetPointMap_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback GetPointMap_ResponseSubscriptionCallback) (*GetPointMap_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg GetPointMap_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, GetPointMap_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &GetPointMap_ResponseSubscription{sub}, nil
}

func (s *GetPointMap_ResponseSubscription) TakeMessage(out *GetPointMap_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneGetPointMap_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneGetPointMap_ResponseSlice(dst, src []GetPointMap_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var GetPointMap_ResponseTypeSupport types.MessageTypeSupport = _GetPointMap_ResponseTypeSupport{}

type _GetPointMap_ResponseTypeSupport struct{}

func (t _GetPointMap_ResponseTypeSupport) New() types.Message {
	return NewGetPointMap_Response()
}

func (t _GetPointMap_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.map_msgs__srv__GetPointMap_Response
	return (unsafe.Pointer)(C.map_msgs__srv__GetPointMap_Response__create())
}

func (t _GetPointMap_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.map_msgs__srv__GetPointMap_Response__destroy((*C.map_msgs__srv__GetPointMap_Response)(pointer_to_free))
}

func (t _GetPointMap_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*GetPointMap_Response)
	mem := (*C.map_msgs__srv__GetPointMap_Response)(dst)
	sensor_msgs_msg.PointCloud2TypeSupport.AsCStruct(unsafe.Pointer(&mem._map), &m.Map)
}

func (t _GetPointMap_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*GetPointMap_Response)
	mem := (*C.map_msgs__srv__GetPointMap_Response)(ros2_message_buffer)
	sensor_msgs_msg.PointCloud2TypeSupport.AsGoStruct(&m.Map, unsafe.Pointer(&mem._map))
}

func (t _GetPointMap_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__map_msgs__srv__GetPointMap_Response())
}

type CGetPointMap_Response = C.map_msgs__srv__GetPointMap_Response
type CGetPointMap_Response__Sequence = C.map_msgs__srv__GetPointMap_Response__Sequence

func GetPointMap_Response__Sequence_to_Go(goSlice *[]GetPointMap_Response, cSlice CGetPointMap_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]GetPointMap_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		GetPointMap_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func GetPointMap_Response__Sequence_to_C(cSlice *CGetPointMap_Response__Sequence, goSlice []GetPointMap_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.map_msgs__srv__GetPointMap_Response)(C.malloc(C.sizeof_struct_map_msgs__srv__GetPointMap_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		GetPointMap_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func GetPointMap_Response__Array_to_Go(goSlice []GetPointMap_Response, cSlice []CGetPointMap_Response) {
	for i := 0; i < len(cSlice); i++ {
		GetPointMap_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func GetPointMap_Response__Array_to_C(cSlice []CGetPointMap_Response, goSlice []GetPointMap_Response) {
	for i := 0; i < len(goSlice); i++ {
		GetPointMap_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
