// Code generated by rclgo-gen. DO NOT EDIT.

package map_msgs_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <map_msgs/srv/projected_maps_info.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/ATIinc/rclgo/pkg/rclgo"
	"github.com/ATIinc/rclgo/pkg/rclgo/typemap"
	"github.com/ATIinc/rclgo/pkg/rclgo/types"
)

func init() {
	typemap.RegisterService("map_msgs/ProjectedMapsInfo", ProjectedMapsInfoTypeSupport)
	typemap.RegisterService("map_msgs/srv/ProjectedMapsInfo", ProjectedMapsInfoTypeSupport)
}

type _ProjectedMapsInfoTypeSupport struct {}

func (s _ProjectedMapsInfoTypeSupport) Request() types.MessageTypeSupport {
	return ProjectedMapsInfo_RequestTypeSupport
}

func (s _ProjectedMapsInfoTypeSupport) Response() types.MessageTypeSupport {
	return ProjectedMapsInfo_ResponseTypeSupport
}

func (s _ProjectedMapsInfoTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__map_msgs__srv__ProjectedMapsInfo())
}

// Modifying this variable is undefined behavior.
var ProjectedMapsInfoTypeSupport types.ServiceTypeSupport = _ProjectedMapsInfoTypeSupport{}

// ProjectedMapsInfoClient wraps rclgo.Client to provide type safe helper
// functions
type ProjectedMapsInfoClient struct {
	*rclgo.Client
}

// NewProjectedMapsInfoClient creates and returns a new client for the
// ProjectedMapsInfo
func NewProjectedMapsInfoClient(node *rclgo.Node, serviceName string, options *rclgo.ClientOptions) (*ProjectedMapsInfoClient, error) {
	client, err := node.NewClient(serviceName, ProjectedMapsInfoTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &ProjectedMapsInfoClient{client}, nil
}

func (s *ProjectedMapsInfoClient) Send(ctx context.Context, req *ProjectedMapsInfo_Request) (*ProjectedMapsInfo_Response, *rclgo.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*ProjectedMapsInfo_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type ProjectedMapsInfoServiceResponseSender struct {
	sender rclgo.ServiceResponseSender
}

func (s ProjectedMapsInfoServiceResponseSender) SendResponse(resp *ProjectedMapsInfo_Response) error {
	return s.sender.SendResponse(resp)
}

type ProjectedMapsInfoServiceRequestHandler func(*rclgo.ServiceInfo, *ProjectedMapsInfo_Request, ProjectedMapsInfoServiceResponseSender)

// ProjectedMapsInfoService wraps rclgo.Service to provide type safe helper
// functions
type ProjectedMapsInfoService struct {
	*rclgo.Service
}

// NewProjectedMapsInfoService creates and returns a new service for the
// ProjectedMapsInfo
func NewProjectedMapsInfoService(node *rclgo.Node, name string, options *rclgo.ServiceOptions, handler ProjectedMapsInfoServiceRequestHandler) (*ProjectedMapsInfoService, error) {
	h := func(rmw *rclgo.ServiceInfo, msg types.Message, rs rclgo.ServiceResponseSender) {
		m := msg.(*ProjectedMapsInfo_Request)
		responseSender := ProjectedMapsInfoServiceResponseSender{sender: rs}
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, ProjectedMapsInfoTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &ProjectedMapsInfoService{service}, nil
}
