// Code generated by rclgo-gen. DO NOT EDIT.

package map_msgs_srv
import (
	"unsafe"

	"github.com/ATIinc/rclgo/pkg/rclgo"
	"github.com/ATIinc/rclgo/pkg/rclgo/types"
	"github.com/ATIinc/rclgo/pkg/rclgo/typemap"
	map_msgs_msg "github.com/iema-group/goros2/msgs/map_msgs/msg"
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <map_msgs/srv/set_map_projections.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("map_msgs/SetMapProjections_Response", SetMapProjections_ResponseTypeSupport)
	typemap.RegisterMessage("map_msgs/srv/SetMapProjections_Response", SetMapProjections_ResponseTypeSupport)
}

type SetMapProjections_Response struct {
	ProjectedMapsInfo []map_msgs_msg.ProjectedMapInfo `yaml:"projected_maps_info" json:"projected_maps_info" mapstructure:"projected_maps_info"`
}

// NewSetMapProjections_Response creates a new SetMapProjections_Response with default values.
func NewSetMapProjections_Response() *SetMapProjections_Response {
	self := SetMapProjections_Response{}
	self.SetDefaults()
	return &self
}

func (t *SetMapProjections_Response) Clone() *SetMapProjections_Response {
	c := &SetMapProjections_Response{}
	if t.ProjectedMapsInfo != nil {
		c.ProjectedMapsInfo = make([]map_msgs_msg.ProjectedMapInfo, len(t.ProjectedMapsInfo))
		map_msgs_msg.CloneProjectedMapInfoSlice(c.ProjectedMapsInfo, t.ProjectedMapsInfo)
	}
	return c
}

func (t *SetMapProjections_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *SetMapProjections_Response) SetDefaults() {
	t.ProjectedMapsInfo = nil
}

func (t *SetMapProjections_Response) GetTypeSupport() types.MessageTypeSupport {
	return SetMapProjections_ResponseTypeSupport
}

// SetMapProjections_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type SetMapProjections_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewSetMapProjections_ResponsePublisher creates and returns a new publisher for the
// SetMapProjections_Response
func NewSetMapProjections_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*SetMapProjections_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, SetMapProjections_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &SetMapProjections_ResponsePublisher{pub}, nil
}

func (p *SetMapProjections_ResponsePublisher) Publish(msg *SetMapProjections_Response) error {
	return p.Publisher.Publish(msg)
}

// SetMapProjections_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type SetMapProjections_ResponseSubscription struct {
	*rclgo.Subscription
}

// SetMapProjections_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a SetMapProjections_ResponseSubscription.
type SetMapProjections_ResponseSubscriptionCallback func(msg *SetMapProjections_Response, info *rclgo.MessageInfo, err error)

// NewSetMapProjections_ResponseSubscription creates and returns a new subscription for the
// SetMapProjections_Response
func NewSetMapProjections_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback SetMapProjections_ResponseSubscriptionCallback) (*SetMapProjections_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg SetMapProjections_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, SetMapProjections_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &SetMapProjections_ResponseSubscription{sub}, nil
}

func (s *SetMapProjections_ResponseSubscription) TakeMessage(out *SetMapProjections_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneSetMapProjections_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneSetMapProjections_ResponseSlice(dst, src []SetMapProjections_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var SetMapProjections_ResponseTypeSupport types.MessageTypeSupport = _SetMapProjections_ResponseTypeSupport{}

type _SetMapProjections_ResponseTypeSupport struct{}

func (t _SetMapProjections_ResponseTypeSupport) New() types.Message {
	return NewSetMapProjections_Response()
}

func (t _SetMapProjections_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.map_msgs__srv__SetMapProjections_Response
	return (unsafe.Pointer)(C.map_msgs__srv__SetMapProjections_Response__create())
}

func (t _SetMapProjections_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.map_msgs__srv__SetMapProjections_Response__destroy((*C.map_msgs__srv__SetMapProjections_Response)(pointer_to_free))
}

func (t _SetMapProjections_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*SetMapProjections_Response)
	mem := (*C.map_msgs__srv__SetMapProjections_Response)(dst)
	map_msgs_msg.ProjectedMapInfo__Sequence_to_C((*map_msgs_msg.CProjectedMapInfo__Sequence)(unsafe.Pointer(&mem.projected_maps_info)), m.ProjectedMapsInfo)
}

func (t _SetMapProjections_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*SetMapProjections_Response)
	mem := (*C.map_msgs__srv__SetMapProjections_Response)(ros2_message_buffer)
	map_msgs_msg.ProjectedMapInfo__Sequence_to_Go(&m.ProjectedMapsInfo, *(*map_msgs_msg.CProjectedMapInfo__Sequence)(unsafe.Pointer(&mem.projected_maps_info)))
}

func (t _SetMapProjections_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__map_msgs__srv__SetMapProjections_Response())
}

type CSetMapProjections_Response = C.map_msgs__srv__SetMapProjections_Response
type CSetMapProjections_Response__Sequence = C.map_msgs__srv__SetMapProjections_Response__Sequence

func SetMapProjections_Response__Sequence_to_Go(goSlice *[]SetMapProjections_Response, cSlice CSetMapProjections_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]SetMapProjections_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		SetMapProjections_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func SetMapProjections_Response__Sequence_to_C(cSlice *CSetMapProjections_Response__Sequence, goSlice []SetMapProjections_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.map_msgs__srv__SetMapProjections_Response)(C.malloc(C.sizeof_struct_map_msgs__srv__SetMapProjections_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		SetMapProjections_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func SetMapProjections_Response__Array_to_Go(goSlice []SetMapProjections_Response, cSlice []CSetMapProjections_Response) {
	for i := 0; i < len(cSlice); i++ {
		SetMapProjections_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func SetMapProjections_Response__Array_to_C(cSlice []CSetMapProjections_Response, goSlice []SetMapProjections_Response) {
	for i := 0; i < len(goSlice); i++ {
		SetMapProjections_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
