# Automatically generated by: ros2nix --distro jazzy --flake
{ lib, buildRosPackage, ament-cmake, ament-lint-auto, ros-gz-example-description }:
buildRosPackage rec {
  pname = "ros-jazzy-ros-gz-example-gazebo";
  version = "0.0.0";

  src = ./.;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  checkInputs = [ ament-lint-auto ];
  propagatedBuildInputs = [ ros-gz-example-description ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "Gazebo-specific implementations for the ros_gz_example project";
    license = with lib.licenses; [ asl20 ];
  };
}
