// Code generated by rclgo-gen. DO NOT EDIT.

package visualization_msgs_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <visualization_msgs/srv/get_interactive_markers.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/ATIinc/rclgo/pkg/rclgo"
	"github.com/ATIinc/rclgo/pkg/rclgo/typemap"
	"github.com/ATIinc/rclgo/pkg/rclgo/types"
)

func init() {
	typemap.RegisterService("visualization_msgs/GetInteractiveMarkers", GetInteractiveMarkersTypeSupport)
	typemap.RegisterService("visualization_msgs/srv/GetInteractiveMarkers", GetInteractiveMarkersTypeSupport)
}

type _GetInteractiveMarkersTypeSupport struct {}

func (s _GetInteractiveMarkersTypeSupport) Request() types.MessageTypeSupport {
	return GetInteractiveMarkers_RequestTypeSupport
}

func (s _GetInteractiveMarkersTypeSupport) Response() types.MessageTypeSupport {
	return GetInteractiveMarkers_ResponseTypeSupport
}

func (s _GetInteractiveMarkersTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__visualization_msgs__srv__GetInteractiveMarkers())
}

// Modifying this variable is undefined behavior.
var GetInteractiveMarkersTypeSupport types.ServiceTypeSupport = _GetInteractiveMarkersTypeSupport{}

// GetInteractiveMarkersClient wraps rclgo.Client to provide type safe helper
// functions
type GetInteractiveMarkersClient struct {
	*rclgo.Client
}

// NewGetInteractiveMarkersClient creates and returns a new client for the
// GetInteractiveMarkers
func NewGetInteractiveMarkersClient(node *rclgo.Node, serviceName string, options *rclgo.ClientOptions) (*GetInteractiveMarkersClient, error) {
	client, err := node.NewClient(serviceName, GetInteractiveMarkersTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &GetInteractiveMarkersClient{client}, nil
}

func (s *GetInteractiveMarkersClient) Send(ctx context.Context, req *GetInteractiveMarkers_Request) (*GetInteractiveMarkers_Response, *rclgo.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*GetInteractiveMarkers_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type GetInteractiveMarkersServiceResponseSender struct {
	sender rclgo.ServiceResponseSender
}

func (s GetInteractiveMarkersServiceResponseSender) SendResponse(resp *GetInteractiveMarkers_Response) error {
	return s.sender.SendResponse(resp)
}

type GetInteractiveMarkersServiceRequestHandler func(*rclgo.ServiceInfo, *GetInteractiveMarkers_Request, GetInteractiveMarkersServiceResponseSender)

// GetInteractiveMarkersService wraps rclgo.Service to provide type safe helper
// functions
type GetInteractiveMarkersService struct {
	*rclgo.Service
}

// NewGetInteractiveMarkersService creates and returns a new service for the
// GetInteractiveMarkers
func NewGetInteractiveMarkersService(node *rclgo.Node, name string, options *rclgo.ServiceOptions, handler GetInteractiveMarkersServiceRequestHandler) (*GetInteractiveMarkersService, error) {
	h := func(rmw *rclgo.ServiceInfo, msg types.Message, rs rclgo.ServiceResponseSender) {
		m := msg.(*GetInteractiveMarkers_Request)
		responseSender := GetInteractiveMarkersServiceResponseSender{sender: rs}
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, GetInteractiveMarkersTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &GetInteractiveMarkersService{service}, nil
}
