// Code generated by rclgo-gen. DO NOT EDIT.

package visualization_msgs_srv
import (
	"unsafe"

	"github.com/ATIinc/rclgo/pkg/rclgo"
	"github.com/ATIinc/rclgo/pkg/rclgo/types"
	"github.com/ATIinc/rclgo/pkg/rclgo/typemap"
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <visualization_msgs/srv/get_interactive_markers.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("visualization_msgs/GetInteractiveMarkers_Request", GetInteractiveMarkers_RequestTypeSupport)
	typemap.RegisterMessage("visualization_msgs/srv/GetInteractiveMarkers_Request", GetInteractiveMarkers_RequestTypeSupport)
}

type GetInteractiveMarkers_Request struct {
}

// NewGetInteractiveMarkers_Request creates a new GetInteractiveMarkers_Request with default values.
func NewGetInteractiveMarkers_Request() *GetInteractiveMarkers_Request {
	self := GetInteractiveMarkers_Request{}
	self.SetDefaults()
	return &self
}

func (t *GetInteractiveMarkers_Request) Clone() *GetInteractiveMarkers_Request {
	c := &GetInteractiveMarkers_Request{}
	return c
}

func (t *GetInteractiveMarkers_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *GetInteractiveMarkers_Request) SetDefaults() {
}

func (t *GetInteractiveMarkers_Request) GetTypeSupport() types.MessageTypeSupport {
	return GetInteractiveMarkers_RequestTypeSupport
}

// GetInteractiveMarkers_RequestPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type GetInteractiveMarkers_RequestPublisher struct {
	*rclgo.Publisher
}

// NewGetInteractiveMarkers_RequestPublisher creates and returns a new publisher for the
// GetInteractiveMarkers_Request
func NewGetInteractiveMarkers_RequestPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*GetInteractiveMarkers_RequestPublisher, error) {
	pub, err := node.NewPublisher(topic_name, GetInteractiveMarkers_RequestTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &GetInteractiveMarkers_RequestPublisher{pub}, nil
}

func (p *GetInteractiveMarkers_RequestPublisher) Publish(msg *GetInteractiveMarkers_Request) error {
	return p.Publisher.Publish(msg)
}

// GetInteractiveMarkers_RequestSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type GetInteractiveMarkers_RequestSubscription struct {
	*rclgo.Subscription
}

// GetInteractiveMarkers_RequestSubscriptionCallback type is used to provide a subscription
// handler function for a GetInteractiveMarkers_RequestSubscription.
type GetInteractiveMarkers_RequestSubscriptionCallback func(msg *GetInteractiveMarkers_Request, info *rclgo.MessageInfo, err error)

// NewGetInteractiveMarkers_RequestSubscription creates and returns a new subscription for the
// GetInteractiveMarkers_Request
func NewGetInteractiveMarkers_RequestSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback GetInteractiveMarkers_RequestSubscriptionCallback) (*GetInteractiveMarkers_RequestSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg GetInteractiveMarkers_Request
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, GetInteractiveMarkers_RequestTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &GetInteractiveMarkers_RequestSubscription{sub}, nil
}

func (s *GetInteractiveMarkers_RequestSubscription) TakeMessage(out *GetInteractiveMarkers_Request) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneGetInteractiveMarkers_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneGetInteractiveMarkers_RequestSlice(dst, src []GetInteractiveMarkers_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var GetInteractiveMarkers_RequestTypeSupport types.MessageTypeSupport = _GetInteractiveMarkers_RequestTypeSupport{}

type _GetInteractiveMarkers_RequestTypeSupport struct{}

func (t _GetInteractiveMarkers_RequestTypeSupport) New() types.Message {
	return NewGetInteractiveMarkers_Request()
}

func (t _GetInteractiveMarkers_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.visualization_msgs__srv__GetInteractiveMarkers_Request
	return (unsafe.Pointer)(C.visualization_msgs__srv__GetInteractiveMarkers_Request__create())
}

func (t _GetInteractiveMarkers_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.visualization_msgs__srv__GetInteractiveMarkers_Request__destroy((*C.visualization_msgs__srv__GetInteractiveMarkers_Request)(pointer_to_free))
}

func (t _GetInteractiveMarkers_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	
}

func (t _GetInteractiveMarkers_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	
}

func (t _GetInteractiveMarkers_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__visualization_msgs__srv__GetInteractiveMarkers_Request())
}

type CGetInteractiveMarkers_Request = C.visualization_msgs__srv__GetInteractiveMarkers_Request
type CGetInteractiveMarkers_Request__Sequence = C.visualization_msgs__srv__GetInteractiveMarkers_Request__Sequence

func GetInteractiveMarkers_Request__Sequence_to_Go(goSlice *[]GetInteractiveMarkers_Request, cSlice CGetInteractiveMarkers_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]GetInteractiveMarkers_Request, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		GetInteractiveMarkers_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func GetInteractiveMarkers_Request__Sequence_to_C(cSlice *CGetInteractiveMarkers_Request__Sequence, goSlice []GetInteractiveMarkers_Request) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.visualization_msgs__srv__GetInteractiveMarkers_Request)(C.malloc(C.sizeof_struct_visualization_msgs__srv__GetInteractiveMarkers_Request * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		GetInteractiveMarkers_RequestTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func GetInteractiveMarkers_Request__Array_to_Go(goSlice []GetInteractiveMarkers_Request, cSlice []CGetInteractiveMarkers_Request) {
	for i := 0; i < len(cSlice); i++ {
		GetInteractiveMarkers_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func GetInteractiveMarkers_Request__Array_to_C(cSlice []CGetInteractiveMarkers_Request, goSlice []GetInteractiveMarkers_Request) {
	for i := 0; i < len(goSlice); i++ {
		GetInteractiveMarkers_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
